version: "3.3"

volumes:
  fsData: {}
  
services:

  storageservicedb:
    build: "./db"
    restart: "always"
    container_name: "storageservicedb"
    environment:
      POSTGRES_DB: "fsdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
    - "5861:5432"
    volumes:
      - fsData:/var/lib/postgresql/data
  fsservice:
    build: "./fs_flask"
    restart: "always"
    container_name: "fsService"
    ports:
    - "9191:9191"
    volumes:
      - /home/ubuntu/storage/files_service:/storage
    depends_on:
      - storageservicedb      
